package keys

const (
	PowerOff    = "KEY_POWEROFF"
	PowerOn     = "KEY_POWERON"
	PowerToggle = "KEY_POWER"
	Home        = "KEY_HOME"
	Menu        = "KEY_MENU"
	Source      = "KEY_SOURCE"
	Guide       = "KEY_GUIDE"
	ChannelList = "KEY_CH_LIST"
	Up          = "KEY_UP"
	Down        = "KEY_DOWN"
	Left        = "KEY_LEFT"
	Right       = "KEY_RIGHT"
	Enter       = "KEY_ENTER"
	Tools       = "KEY_TOOLS"
	Return      = "KEY_RETURN"
	Exit        = "KEY_EXIT"
	Info        = "KEY_INFO"
	Red         = "KEY_RED"
	Green       = "KEY_GREEN"
	Yellow      = "KEY_YELLOW"
	Blue        = "KEY_BLUE"
	VolumeUp    = "KEY_VOLUP"
	VolumeDown  = "KEY_VOLDOWN"
	Mute        = "KEY_MUTE"
	ChannelUp   = "KEY_CHUP"
	ChannelDown = "KEY_CHDOWN"
)
